### ISSUE TITLE
Need variable initialization before use

### ISSUE THREAD

**Issue by JonHass** [DMTF/Redfish-Mockup-Creator#11]
- In redfishMockupCreate.py there were several instances where variables were used before initialization resulting in program halt. 
(George Ericson) did the following to resolve locally and proceed ... need to make these changes to source.
In Main, I added:
absPath=None 
In addHeaderFile, I added:
rc=0
In addTimeFile, I added:
rc=0

**Comment by JonHass** [comment]
I will
#  rhost Redfish Protocol Versions: GET /redfish
# rhost: 10.35.176.72
# full directory path: /root/mockup-creation/14G
# description: This is a mockup of a real new 14G server
# starting mockup creation
# Creating /redfish resource
Traceback (most recent call last):
  File "redfishMockupCreate.py", line 626, in <module>
    main(sys.argv)
  File "redfishMockupCreate.py", line 302, in main
    addHeaderFile(addHeaders, r, dirPath)
  File "redfishMockupCreate.py", line 79, in addHeaderFile
    return rc
UnboundLocalError: local variable 'rc' referenced before assignment

**Comment by billdodd** [comment]
Just confirming that the traceback Jon reports above is fixed by the change in the pending Pull request from @GEricson.

**Comment by mraineri** [comment]
Fixed with PR #12
