### ISSUE TITLE
parsing error for odata.type of collections

### ISSUE THREAD

**Issue by joergweed** [DMTF/Redfish-Mockup-Creator#15]
The parsing of odata.type in function parseOdataType of redfishtoolTransport.py is too restrictive, it expects a version number as part of the string, but collection types don't have this, hence error thrown:

 redfishMockupCreate: Transport:parseOdataType: Error parsing @odata.type

Example resource snippet throwing the error:

    "LogServices": {
        "Members": [
            {
                "@odata.id": "/redfish/v1/Managers/1/LogServices/AuditLog/"
            }
        ],
        "@odata.type": "#LogServiceCollection.LogServiceCollection",
        "@odata.id": "/redfish/v1/Managers/1/LogServices/",
        "Members@odata.count": 1,
        "Members@odata.navigationLink": "/redfish/v1/Managers/1/LogServices/Members",
        "Name": "LogServices",
        "@odata.context": "/redfish/v1/$metadata#LogServiceCollection.LogServiceCollection"
    },

**Comment by mraineri** [comment]
Assigning to Bill
