### ISSUE TITLE
tool not grabbing registries and schema file location

### ISSUE THREAD

**Issue by samerhaj** [DMTF/Redfish-Mockup-Creator#19]
The tool parses the Registries collection, and grabs the MessageRegistryFileCollection entries for each registry, but it does not continue to grab the actual registry file from the Location property in the MessageRegistryFile

Same for JsonSchemas collection: Tje JsonSchemaFile is downloaded, but not the actual JSON schema file pointed to by the Location property

**Comment by mraineri** [comment]
The tool should end up following the "Uri" property to grab these; the other URIs are most likely outside of the service, so it wouldn't be good to grab those.

**Comment by samerhaj** [comment]
Any update on this? The mockups created form the tool are not including the actual registry files (like MessageRegistry and AttributeRegistry), which greatly limits the usefulness of the mockups when running in the service emulator

**Comment by billdodd** [comment]
I started looking at this one today.
