### ISSUE TITLE
OEM resources are not captured

### ISSUE THREAD

**Issue by samerhaj** [DMTF/Redfish-Mockup-Creator#20]
The tool is not parsing or downloading any Oem resources. To be a complete mockup capture, the tool should include Oem resources at all levels, including Oem JsonSchema and registries

**Comment by mraineri** [comment]
Should be doable; any time the tool finds an `@odata.id` in the OEM context, it can follow it to get an OEM resource.

**Comment by samerhaj** [comment]
Any update on when this can be added? This is limiting the usefulness of the tool on real implementations that have many Oem resources
