### ISSUE TITLE
Add average and max/min response time statistics

### ISSUE THREAD

**Issue by samerhaj** [DMTF/Redfish-Mockup-Creator#22]
Even though this is a Mockup Creator tool, it does have a very neat feature for measuring and recording the response time for each resource (with -T). It would be useful to add an option to go through all time.json files, and measure the avergae/min/max response times across the entire captured mockup, and print/reocrd the results in README output file

**Comment by mraineri** [comment]
Seems useful; would like to add in the future

**Comment by mraineri** [comment]
Added via #25
