### ISSUE TITLE
0.9.2 is not creading headers, copyright, or pretty format for service root, ...

### ISSUE THREAD

**Issue by pwvancil** [DMTF/Redfish-Mockup-Creator#3]
The top-level APIs are not getting headers, timing, copyright tags, and json pretty formatting:
/redfish/v1 --root service
/redfish/v1/odata
/redfish/v1/$metadata
.
and noting that the way copyright is done in the xml is different.

**Comment by mraineri** [comment]
Should be fixed in open PR

**Comment by mraineri** [comment]
Addressed by PR #9
