### ISSUE TITLE
Undefined ‘ref’ variable in error path

### ISSUE THREAD

**Issue by billdodd** [DMTF/Redfish-Mockup-Creator#32]
When running the mockup creator against systems at Plugfest 2018, I hit an exception due to an undefined variable 'ref' at line 430:

```
    rft.printErr("ERROR: cant parse /redfish/v1/$metadata, cannot scrape the metadata for xml".format(str(ref.tag)))
```

The `.format()` in the line isn't needed at all. It's probably left over from a copy-and-paste.

**Comment by mraineri** [comment]
Resolved in latest PR
