### ISSUE TITLE
Allow starting discovery at \redfish\v1 instead of \redfish

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Mockup-Creator#42]
Since the contents of "\redfish\" are known today, allowing the tool to create a mockup starting from \redfish\v1 would be helpful.  If the creator can't read \redfish - just create the known json content, or better, provide an option to just begin the crawl at \redfish\v1 (or whatever protocol version perhaps).

**Comment by mraineri** [comment]
An option for this would be better since it would require a user to knowingly bypass normal Redfish semantics.

Would like to verify that URIs like /redfish/v1/$metadata and /redfish/v1/odata do not cause the tool to crash when not present.

**Comment by mraineri** [comment]
More follow-up; maybe just print an ERROR if /redfish is not found, but keep going.

**Comment by billdodd** [comment]
> An option for this would be better since it would require a user to knowingly bypass normal Redfish semantics.
> 
> Would like to verify that URIs like /redfish/v1/$metadata and /redfish/v1/odata do not cause the tool to crash when not present.

I verified that the tool reports an error and continues with mockup creation if  `/redfish/v1/$metadata` or `/redfish/v1/odata` are not present.
