### ISSUE TITLE
Mockup creator should be more resilient against bad top-level responses

### ISSUE THREAD

**Issue by alansill** [DMTF/Redfish-Mockup-Creator#50]
In working with various new products, I have found that the mockup creator is hard to use on initial works in progress, for example when the top-level /redfish and /redfish/v1/ responses are not properly formed. 

I'd like to see the mockup creator be made more resilient against such errors, as long as a response to a definite endpoint like /redfish/v1/ exists and is well formed.

**Comment by mraineri** [comment]
@alansill please verify the merged PR addresses your issue; if it does we can close this issue.

**Comment by mraineri** [comment]
Closing; @alansill if the PR did not address your issue, please reopen.
