### ISSUE TITLE
how to compare two output folders from two servers 

### ISSUE THREAD

**Issue by wushuzh** [DMTF/Redfish-Mockup-Creator#61]
Hello,

If there is any tool from DMTF to do further analysis of output from redfish-mockupp-creator to get a higher view of the server ?

I've use creator to "clone" serveral server's redfish services. But it become more difficult for me to tell the differences between all these cloned output folders and manage the "lifecycle" for them. 

- I wonder if there is any existing tools from DMTF can help me on this 
- or if there is no such tool, is it possible to share your suggestion on how to implement more generic algorithm to implement this properly by myself ?

I have multi vendors of redfish creator's outputs. But I think the comparison is more relevant when I want to confirm the similarity from two outputs from same vendor and same SKU.

1. the outputs are from same server, the version 1 and version 2 with bug fixed, then it would be useful to tell if everything is identical, with very few differences (bug fix or a few addition/removal), In this case, I may delete version 1 output folder.

2. the outputs are from two servers with same(almost) hareware spec, in this case, I will assume the two output folders are same as long as the folder structures are same, we can safely ignoring the device id/naming number/nic MAC address differences in this case. I may safely delete any of these servers.

3. the output are from two servers (same vendor, same SKU) with different spec, for example, one server has more/fewer harddisk, more/few PCIe, more/fewer NetwokAdapter etc. If it's possible to get the "similarity scores/metrics" among them, I can make my decision more eaiser.

**Comment by mraineri** [comment]
There's no DMTF tool, but there are general directory comparison methods the Linux community uses for this.

Here's one example: https://stackoverflow.com/questions/4997693/given-two-directory-trees-how-can-i-find-out-which-files-differ-by-content

**Comment by wushuzh** [comment]
Yes, the diff will work in some sense. Thanks for the suggestion.

**Comment by mraineri** [comment]
Discussion during the weekly call: One path could be to make a profile to help ensure certain static properties are present and contain particular values between two systems. Other tools like Beyond Compare or Araxis Merge. As far as the DMTF is concerned though, there's not a strong desire to create a Redfish specific comparison tool.
