### ISSUE TITLE
How does it work

### ISSUE THREAD

**Issue by watdafrag** [DMTF/Redfish-Mockup-Creator#64]
Basically i have to make a program that establishes a connection with the mockup server. For now, i can simply call the local endpoints with a basic get. Where can i find the redfish credentials to insert into the mockup creator command?

**Comment by mraineri** [comment]
A mockup server usually doesn't need credentials. Typically if you're using this tool, you're interacting with a live service, and would normally need credentials to interact with the service. This would need to come from your system vendor, or the owner of the system who set up the interface.

However, if you do need to direct this tool to point to a mockup server, you should be able to provide any credentials you want. If I remember correctly the Redfish Mockup Server will accept any set of credentials you give it.

**Comment by watdafrag** [comment]
there's something i'm missing. i created the server in a terminal, and everything works fine.. but now i need to create the effetive mockup.. in the readme it's written that i can use this creator along with the mockup-server... but when i launch the creation it says "ERROR: Aborting; could not authenticate with the Redfish service: " because i don't know which credentials shuìould i put... where do i create the user and password?

**Comment by billdodd** [comment]
Specify the `-A None` (no authentication) option for this case. Example:

python redfishMockupCreate.py -r 127.0.0.1:8000  -u "" -p "" -A None -D /tmp/mockup-test -d 'test with mockup'

**Comment by watdafrag** [comment]
@billdodd will check later but i think it will do the job, thanks! exactly what i wanted to  hear

**Comment by mraineri** [comment]
@watdafrag did @billdodd's suggestion work for you?

**Comment by mraineri** [comment]
Closing; no further updates. If more help is needed, please reopen the issue.
