### ISSUE TITLE
failure with special chars in paths

### ISSUE THREAD

**Issue by Flow86** [DMTF/Redfish-Mockup-Creator#72]
Hi,

I'm using Redfish-Mockup-Creator on windows, trying to read a dell poweredge system. The poweredge system contains paths like
`/redfish/v1/Systems/System.Embedded.1/Storage/RAID.Integrated.1-1/Drives/Disk.Bay.7:Enclosure.Internal.0-1:RAID.Integrated.1-1` (note the `:` in there!)

Writing these files to disk on windows fails.
Is there a way to modify the file downloads to have "safe" filenames? (i.e replace any special char with an underscore)

Thank you

**Comment by Flow86** [comment]
I have encountered at least these three: `| : ;`

**Comment by mraineri** [comment]
@Flow86 please try out the branch "special-character-handling"; this change should detect the naming restrictions automatically so you do not need to specify anything new on the command line. From the systems I have available and running on Windows, this seems to address the issue.

**Comment by Flow86** [comment]
Hi,
I've tested it on a few of my systems and it works. Thank you, thats great!

**Comment by mraineri** [comment]
Thanks for confirming! It'll likely get merged later today so it's part of the main release.

**Comment by jautor** [comment]
We'll also open an issue in the Redfish-Service-Validator to throw a warning if it sees these characters in URIs.  While they are "legal" from the RFC and Redfish Specification perspective, they should be discouraged...
