### ISSUE TITLE
Windows does not allow colon in filename and getting not found

### ISSUE THREAD

**Issue by shesamian** [DMTF/Redfish-Mockup-Creator#79]
Windows does not allow a colon `:` in the filename but I have a URL containing a colon. So when I collect the mocks on windows a unicode character is being used instead of colon.

![image](https://github.com/DMTF/Redfish-Mockup-Creator/assets/107954668/0d54a09b-9775-4542-a4e2-0f70d826467a)

When the mocks are served on Linux I am getting "not found" but on Widows I don't get "not found"

![image](https://github.com/DMTF/Redfish-Mockup-Creator/assets/107954668/188313e4-f050-4c0c-a664-eaad56195e13)

This behavior is inconsistent.

Update: I was running using Docker on Windows with `-v` flag. If I run the code directly on Widows it's all fine. Maybe we should add a notice in README about it.

**Comment by mraineri** [comment]
We do try to handle this case here: https://github.com/DMTF/Redfish-Mockup-Creator/blob/main/redfishMockupCreate.py#L29

And later it will filter out disallowed characters for folders, but I don't think we've seen people trying this with Docker under Windows though... Do you happen to know what `sys.platform` contains when run in that type of environment?

**Comment by shesamian** [comment]
![image](https://github.com/DMTF/Redfish-Mockup-Creator/assets/107954668/15395db8-e8ce-4898-a01f-2c6fe2879366)

when we run Docker in Windows, the value of `sys.platform` is Linux:

> docker run -it --entrypoint sh dmtf/redfish-mockup-creator:latest

**Comment by mraineri** [comment]
Thanks for confirming; I assumed it would show up as Linux, but wanted to see if there was something else we might be able to do.

**Comment by mraineri** [comment]
Would it be worth to also add a CLI option to force the directory renaming? Essentially we'd still have the logic in place to automatically rename folders if we're on Windows, but if you want, you can trigger it on demand regardless of your OS.

**Comment by shesamian** [comment]
I think that would be a great idea to add an optional boolean flag to force the directory renaming. I was able to fix my problem but just running the Python code directly on Windows instead of running it via `docker run`. Thank you so much again for the quick response and follow-up.
